### ISSUE TITLE
	Add a structured wiki, include components and workflows, ex. updateing blockchain metadata, implementing custom pallets, implementing custom types ....

### ISSUE THREAD

**Issue by svnscha** [JetonNetwork/Open-Grants-Program#17]

**Comment by darkfriend77** [comment]
https://github.com/JetonNetwork/SubstrateNetApi/wiki/Extension#extension
https://github.com/JetonNetwork/SubstrateNetApi/wiki/Types#custom-type
https://github.com/JetonNetwork/SubstrateNetApi/wiki/Usage#access-metadata-as-json-chain-specific
