### ISSUE TITLE
Article and Blog about this open grant and the deliverables, at least one deep dive post into each milestone subject area, SubstrateNetApi, GameEngine, ServiceLayer & ConnectFour (if accpeted)

### ISSUE THREAD

**Issue by svnscha** [JetonNetwork/Open-Grants-Program#22]

**Comment by darkfriend77** [comment]
We should have a blog here, which mentions our progress. @metastar77 as part of the Polkadot Play website.

**Comment by darkfriend77** [comment]
https://medium.com/polkadot-play/project-introduction-681820988416

**Comment by darkfriend77** [comment]
https://medium.polkadotplay.com/w3f-open-grant-substratenetapi-85701e9e6494
