### ISSUE TITLE
Extend Generic Types for Vec & Option

### ISSUE THREAD

**Issue by svnscha** [JetonNetwork/Open-Grants-Program#6]

**Comment by darkfriend77** [comment]
https://github.com/JetonNetwork/SubstrateNetApi/blob/origin/SubstrateNetApi/Model/Types/Struct/Option.cs

https://github.com/JetonNetwork/SubstrateNetApi/blob/origin/SubstrateNetApi/Model/Types/Struct/Vec.cs
