### ISSUE TITLE
Implement Rust special enums, who are used like structs

### ISSUE THREAD

**Issue by svnscha** [JetonNetwork/Open-Grants-Program#9]

**Comment by darkfriend77** [comment]
One way to integrate does enums,
https://github.com/JetonNetwork/SubstrateNetApi/blob/origin/SubstrateNetApi/Model/Types/ExtEnumType.cs

the other way would be like this,
https://github.com/JetonNetwork/SubstrateNetApi/blob/origin/SubstrateNetApi/Model/Types/Struct/Phase.cs
